{
 "title": "SimplyTimed vs Timed Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Performance by Service",
   "type": "graph",
   "description": "Calculated purely with SimpleTimed",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(application_de_bender_metrics_HelloResource_simplyTimed_elapsedTime_seconds[3m]) / rate(application_de_bender_metrics_HelloResource_simplyTimed_total[3m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Performance",
   "type": "graph",
   "description": "Calculated purely with SimpleTimed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,job) (rate(application_de_bender_metrics_HelloResource_simplyTimed_elapsedTime_seconds[3m])) / sum without(instance,job) (rate(application_de_bender_metrics_HelloResource_simplyTimed_total[3m]))",
     "legendFormat": "Avg. ResponseTime"
    }
   ]
  },
  {
   "title": "Mean Performance by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "application_de_bender_metrics_HelloResource_timed_mean_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "!! WRONG !! Overall Performance",
   "type": "graph",
   "description": "Wrong since it calculates the average of means ...",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without(job, instance) (application_de_bender_metrics_HelloResource_timed_mean_seconds) / count without(instance, job) ({__name__=~\"application.*mean_seconds\"})",
     "legendFormat": "Overall-Average??"
    }
   ]
  }
 ]
}