global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: service_a
  static_configs:
    - targets: ['service_a:8080']
- job_name: service_b
  static_configs:
    - targets: ['service_b:8080']
- job_name: service_c
  static_configs:
    - targets: ['service_c:8080']
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
