@startuml
[client] -> REST
REST - [Service]
[Service] - Metrics
Metrics <-- [Prometheus]: scrapes
[Prometheus] <- [Grafana]

note top of [Service]
  Three running instances
  simulating a cluster
  of microservices.
end note

note top of [client]
  cURL (produceSteadyLoad.sh)
  to put some traffic onto
  the deployed service
  instances
end note

note left of [Prometheus]
  Scrapes tbe services in
  intervals of 5 seconds.
end note
@enduml